apiVersion: apps/v1
kind: Deployment
metadata:
  name: toronto-time-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toronto-time-app
  template:
    metadata:
      labels:
        app: toronto-time-app
    spec:
      containers:
      - name: toronto-time-app
        image: arjunneupane/toronto-time-app:v01
        ports:
        - containerPort: 3030
