apiVersion: v1
kind: Service
metadata:
  name: toronto-time-service
spec:
  type: NodePort
  selector:
    app: toronto-time-app
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30300
